config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get 'home' => 'static_pages#home'
  resources :books
  resources :categories

  resources 'users'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  # create API
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :books
      resources :categories do
        get 'books' => 'categories#get_books_by_category' , on: :member
      end
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :category

  validates_presence_of :title, :isbn, :des
  validates :isbn, length: {maximum: 5}
  def self.search(search)
    if search
      self.where("title LIKE ?", "%#{search}%")
    else
      self.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_login
  before_action :get_categories
  before_action :get_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  def index
    @books = Book.order('created_at DESC').search(params[:search]).paginate(page: params[:page], per_page: 10)
  end

  # GET /books/1
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  private

    def get_categories
      @categories = Category.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def get_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :isbn, :des, :category_id)
    end

end

app/controllers/concerns/api/v1/books_controller.rb
class Api::V1::BooksController < ApplicationController
  before_action :get_book, only: [:show, :update, :destroy]


  # GET api/v1/books
  def index
    @books = Book.all

    respond_to do |format|
      format.json {render :index, status: :ok}
    end
  end

  # GET api/v1/categories/:id/books
  def show
    respond_to do |format|
      format.json {render :show, status: :ok}
    end
  end

  #POST api/v1/books
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.json {render :create, status: :created}
      else
        format.json {render json: @book.errors, status: :unprocessable_entity}
      end
    end
  end


  #PUT api/v1/books/:id
  def update

    respond_to do |format|
      if @book.update(book_params)
        format.json {render :show, status: :ok}
      else
        format.json {render json: @book.errors, status: :unprocessable_entity}
      end
    end
  end


  #DELETE api/v1/books/:id
  def destroy
    @book.destroy

    respond_to do |format|
      format.json {head :no_content}
    end
  end

  private

  def get_book
    @book = Book.find_by(id: params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :isbn, :des, :category_id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>Title</th>
    <th>Isbn</th>
    <th>Des</th>
    <th>Category</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%=link_to book.title, book %></td>
      <td><%= book.isbn %></td>
      <td><%= book.des %></td>
      <% if book.category.nil? %>
        <td>No Category</td>
      <% else %>
        <td><%= book.category.category_name %></td>
      <% end %>
        <td><%= link_to 'Show', book, class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_book_path(book),class: 'btn btn-info' %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @products %>
<br>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :isbn %><br>
    <%= f.number_field :isbn %>
  </div>
  <div class="form-group">
    <%= f.label :des %><br>
    <%= f.text_area :des %>
  </div>

  <div class="form-group">
    <%= f.collection_select(:category_id, Category.all, :id, :category_name) %>
    <p><%= link_to 'New Category', new_category_path %></p>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<% if @book.category.nil? %>
  <% breadcrumb :no_category_book, @book %>
<% else %>
  <% breadcrumb :book, @book %>
<% end %>

<div class="page-header">
  <h1>Editing Book</h1>
</div>


<%= render 'form' %>

<%= link_to 'Show', @book, class: 'btn btn-default' %> |
<%= link_to 'Back', books_path, class: 'btn btn-default' %>

app/views/books/index.html.erb
<% breadcrumb :root %>

<div class="page-header">
  <h1>Books</h1>
</div>

<%= form_tag books_path, method: 'get', id: "books_search", remote: true do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :title => nil %>
  </p>
<% end %>

<div id="books"><%= render 'books' %></div>

<%= link_to 'New Book', new_book_path, class: 'btn btn-default' %>

app/views/books/index.js.erb
$("#books").html("<%= escape_javascript(render("books")) %>");
$("#books").show();

app/views/books/new.html.erb
<% breadcrumb :new_book %>
<div class="page-header">
  <h1>New Book</h1>
</div>


<%= render 'form' %>

<%= link_to 'Back', books_path, class: 'btn btn-default' %>

app/views/books/show.html.erb
<% if @book.category.nil? %>
  <% breadcrumb :no_category_book, @book %>
<% else %>
  <% breadcrumb :book, @book %>
<% end %>

<div class="page-header">
  <h1><%= @book.title %></h1>
</div>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Des:</strong>
  <%= @book.des %>
</p>

<p>
  <strong>Category:</strong>
  <% if @book.category.nil? %>
  <td>No Category</td>
  <% else %>
  <td><%= @book.category.category_name %></td>
<% end %>
</p>

<%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-default'%> |
<%= link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %> |
<%= link_to 'Back', books_path, class: 'btn btn-default' %>