config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get 'home' => 'static_pages#home'
  resources :books
  resources :categories

  resources 'users'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  # create API
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :books
      resources :categories do
        get 'books' => 'categories#get_books_by_category' , on: :member
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books
	before_destroy :no_reference_books

	validates :category_name, presence: true, uniqueness: true

	private

  def no_reference_books
    unless books.nil?
      books.update_all(category_id: nil)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login
  before_action :get_categories
  before_action :find_category, only: [:edit, :update, :show, :destroy]


  def index
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to books_path
  end

  def edit
  end

  def update
    @category.update(category_params)
    redirect_to @category
  end

  def destroy
    @category.destroy
    redirect_to books_path
  end

  private

  def get_categories
    @categories = Category.all
  end

  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:category_name)
  end
end

app/controllers/concerns/api/v1/categories_controller.rb
class Api::V1::CategoriesController < ApplicationController
  before_action :get_category, only: [:show, :get_books_by_category, :update, :destroy]

  # GET api/v1/categories
  def index
    @categories = Category.all

    respond_to do |format|
      format.json {render :index, status: :ok}
    end
  end

  # GET api/v1/categories/:id
  def show
    respond_to do |format|
      format.json {render :show, status: :ok}
    end
  end

  # GET api/v1/categories/:id/books
  def get_books_by_category
    @books = @category.books
    respond_to do |format|
      format.json {render :get_books_by_category, status: :ok}
    end
  end

  # POST api/v1/categories
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.json {render :create, status: :created}
      else
        format.json {render json: @category.errors, status: :unprocessable_entity}
      end
    end
  end

  # PUT api/v1/categories/:id
  def update

    respond_to do |format|
      if @category.update(category_params)
        format.json {render :show, status: :ok}
      else
        format.json {render json: @category.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE api/v1/category/:id
  def destroy
    @category.destroy

    respond_to do |format|
      format.json {head :no_content}
    end
  end

  private

  def get_category
    @category = Category.find_by(id: params[:id])
  end

  def category_params
    params.require(:category).permit(:category_name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category_name %><br>
    <%= f.text_field :category_name %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% breadcrumb :category, @category %>
<div class="page-header">
  <h1>Editing Category</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @category, class: 'btn btn-default' %> |
<%= link_to 'Back', books_path, class: 'btn btn-default' %>

app/views/categories/index.html.erb
<div class="page-header">
  <h1>Listing Categories</h1>
</div>
<ul class="list-group">
  <% @categories.each do |category| %>
    <li class="list-group-item"><%= link_to category.category_name, category %>
      <% if current_user  %>
        <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-default'%>
        <%= link_to 'Delete', category,method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default'%>
      <% end %>
      <span class="badge"><%= category.books.count %></span>
    </li>
  <% end %>
</ul>

<%= link_to 'New Category', new_category_path, class: 'btn btn-info' %> |
<%= link_to 'Seen Users', users_path, class: 'btn btn-info' %> |
<%= link_to 'Seen Books', books_path, class: 'btn btn-info' %>

app/views/categories/new.html.erb
<% breadcrumb :new_category %>
<div class="page-header">
  <h1>New Category</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', books_path, class: 'btn btn-default' %>

app/views/categories/show.html.erb
<% breadcrumb :category, @category %>
<div class="page-header">
  <h1><%= @category.category_name %></h1>
</div>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Title</th>
    <th>Isbn</th>
    <th>Des</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @category.books.each do |book| %>
    <tr>
      <td><%=link_to book.title, book %></td>
      <td><%= book.isbn %></td>
      <td><%= book.des %></td>
      <td><%= link_to 'Edit', edit_book_path(book),class: 'btn btn-info' %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New Book', new_book_path, class: 'btn btn-default'%>
<%= link_to 'Back', books_path, class: 'btn btn-default' %>