config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get 'home' => 'static_pages#home'
  resources :books
  resources :categories

  resources 'users'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  # create API
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :books
      resources :categories do
        get 'books' => 'categories#get_books_by_category' , on: :member
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookstoreV2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="nav navbar-inverse ">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Book Store", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav pull-right">
      <% if current_user %>
          <li><%= link_to current_user.email %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
      <% else %>
          <li><%= link_to "Log in", login_path %></a></li>
          <li><%= link_to "Sign up", signup_path %></a></li>
      <% end %>
      </ul>
    </div>
  </nav>
  <% if current_user %>
    <div class="container">
       <%= breadcrumbs  display_single_fragment: true, style: :bootstrap %>
    </div>
  <% end %>
  <div class="container">
    <div class="body">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <% if current_user %>
      <div class="body-left">
        <%= render template: 'categories/index' %>
      </div>
      <div class="body-right">
        <%= yield %>
      </div>
      <%else%>
        <div class="body-before">
          <%= yield %>
        </div>

      <% end %>
    </div>
  </div>


</body>
</html>